version: "3.7"
services:
  api:
    container_name: api_container
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=8080
    entrypoint: /start-reload.sh
    volumes:
      - ./api:/app
  ui:
    container_name: ui_container
    build: ./ui
    volumes:
      - "./ui:/app"
      - "/app/node_modules"

    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    stdin_open: true

    # For package update use:
    #   docker-compose down -v
    #   docker-compose up -d --build
